import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './utils/providers';
import { FavoritesProvider } from './utils/favoritesProvider';
import AdSenseScript from './utils/AdSenseScript';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    // Google AdSense 계정 확인용 메타 태그
    other: {
        'google-adsense-account': 'ca-pub-7246383169537696',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                suppressHydrationWarning
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {/* Google AdSense - data-nscript 미지원으로 일반 script 주입 사용 */}
                <AdSenseScript />
                <Providers>
                    <FavoritesProvider>{children}</FavoritesProvider>
                </Providers>
            </body>
        </html>
    );
}
